#!/bin/bash
# Title: NetRider WiGLE Map
# Description: Self-contained beta: native green map and WiGLE web dashboard.
# Author: Glytch + Codex
# Version: 2.1.2-beta.2
# Category: general

# This file and netrider-bundle.tar.gz are the complete executable payload.
# Generated by tools/package-beta.py; the archive hash is pinned at build time.
set -o pipefail
umask 077
MODE="${1:-}"
EXPECTED_SHA256='bb27899938f6fe6500283d76a4da6ddcb9165d5a94592d65ba23550b0e989626'
PAYLOAD_ROOT="${_PAYLOAD_HOME:-${NETRIDER_PAYLOAD_DIR:-}}"
if [ -z "$PAYLOAD_ROOT" ]; then
  PAYLOAD_ROOT="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)" || exit 1
fi
PAYLOAD_ROOT="${PAYLOAD_ROOT%/}"
BUNDLE="$PAYLOAD_ROOT/netrider-bundle.tar.gz"
CACHE="$PAYLOAD_ROOT/.netrider"
APP_DIR="$CACHE/$EXPECTED_SHA256"

fail() {
  printf 'NetRider: %s\n' "$1" >&2
  if [ "$MODE" != '--prepare' ] && command -v ERROR_DIALOG >/dev/null 2>&1; then
    ERROR_DIALOG "$1"
  fi
  return 1
}

ready() {
  [ -f "$APP_DIR/.ready" ] &&
  [ "$(cat "$APP_DIR/.ready")" = "$EXPECTED_SHA256" ] &&
  [ -f "$APP_DIR/launcher.sh" ] &&
  [ -x "$APP_DIR/runtime/python3" ] &&
  [ -x "$APP_DIR/runtime/usr/bin/python3.11" ] &&
  [ -x "$APP_DIR/runtime/usr/sbin/uhttpd" ]
}

prepare() (
  ready && exit 0
  [ -r "$BUNDLE" ] || { fail 'Bundle missing. Upload netrider-bundle.tar.gz beside payload.sh.'; exit 1; }
  command -v openssl >/dev/null 2>&1 || { fail 'The stock Pager OpenSSL command is missing.'; exit 1; }
  [ ! -L "$CACHE" ] || { fail 'Refusing a symlinked app cache.'; exit 1; }
  mkdir -p "$CACHE" || { fail 'Cannot create the payload-local app cache.'; exit 1; }

  lock="$CACHE/.install-lock"
  stage=''
  if ! mkdir "$lock" 2>/dev/null; then
    # Reclaim only our small lock after a dead installer; never touch app/data.
    owner="$(cat "$lock/pid" 2>/dev/null)"
    if [[ "$owner" =~ ^[0-9]+$ ]] && ! kill -0 "$owner" 2>/dev/null && [ ! -L "$lock" ]; then
      rm -f "$lock/pid" && rmdir "$lock" && mkdir "$lock" || exit 1
    else
      fail 'Bundle setup is already in progress. Try again shortly.'; exit 1
    fi
  fi
  printf '%s\n' "$$" > "$lock/pid"
  cleanup() {
    case "$stage" in "$CACHE"/.unpack.*) rm -rf -- "$stage" ;; esac
    rm -f "$lock/pid"
    rmdir "$lock" 2>/dev/null || true
  }
  trap cleanup EXIT
  trap 'exit 130' INT
  trap 'exit 143' TERM HUP
  ready && exit 0
  [ ! -e "$APP_DIR" ] || { fail 'App cache is incomplete. Remove this payload folder and reinstall with the Loader.'; exit 1; }
  printf 'NetRider: verifying and unpacking the bundled app (first launch only)...\n' >&2
  checksum="$(openssl dgst -sha256 "$BUNDLE" 2>/dev/null)" || { fail 'Could not verify the bundle.'; exit 1; }
  [ "${checksum##* }" = "$EXPECTED_SHA256" ] || { fail 'Bundle checksum failed. Re-upload the matching launcher and archive.'; exit 1; }
  # The build emits regular USTAR files only. Also reject unexpected paths.
  tar -tzf "$BUNDLE" | while IFS= read -r member; do
    case "$member" in app/*) ;; *) exit 1 ;; esac
    case "$member" in *'/../'*|*'/./'*|*'//'*) exit 1 ;; esac
  done || { fail 'Invalid bundle paths.'; exit 1; }
  stage="$(mktemp -d "$CACHE/.unpack.XXXXXX")" || exit 1
  tar -xzf "$BUNDLE" -C "$stage" || { fail 'Cannot unpack bundle. Check free space and retry.'; exit 1; }
  [ -f "$stage/app/launcher.sh" ] && [ -f "$stage/app/www/index.html" ] || { fail 'Incomplete bundle.'; exit 1; }
  chmod 755 "$stage/app/runtime/python3" "$stage/app/runtime/usr/bin/python3.11" \
    "$stage/app/runtime/usr/sbin/uhttpd" "$stage/app/www/cgi-bin/"*.sh || exit 1
  printf '%s\n' "$EXPECTED_SHA256" > "$stage/app/.ready"
  mv "$stage/app" "$APP_DIR" || exit 1
  ready || { fail 'Bundle setup did not complete.'; exit 1; }
)

prepare || exit 1
if [ "$MODE" = '--prepare' ]; then
  printf '%s\n' "$APP_DIR"
  exit 0
fi
# Hash-addressed code can update without replacing cache/settings/certificates.
# Keep the menu's runtime environment scoped to this child, not the firmware.
export _PAYLOAD_HOME="$APP_DIR"
export NETRIDER_PAYLOAD_DIR="$APP_DIR"
export NETRIDER_DATA_DIR="$PAYLOAD_ROOT/data"
exec /bin/bash "$APP_DIR/launcher.sh"
